packages:
  - .
approveBuilds: electron esbuild electron-winstaller
supportedArchitectures:
  os:
    - current
    - darwin
    - win32
    - linux
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
